### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by buttomnutstoast** [fanhqme/PointSetGeneration#7]
Hi,
I tried the code, most things went fine, however, there was an error showing that data/0/64.gz didn't exist. Could you please provide the link to download complete training data or any solutions to the issue? Thanks!

The following is the error message.

> error! data file not exists: ../data/0/64.gz
please KILL THIS PROGRAM otherwise it will bear undefined behaviors
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/twke/repos/PointSetGeneration/depthestimate/BatchFetcher.py", line 70, in run
    self.queue.put(self.work(self.bno%300000))
  File "/home/twke/repos/PointSetGeneration/depthestimate/BatchFetcher.py", line 37, in work
    assert False,"data file not exists: %s"%path
AssertionError: data file not exists: ../data/0/64.gz

**Comment by jingluwang** [comment]
Same request.
It seems training data in ./data directory are not complete.
Could you please provide all the training data?
In addition, some sample data (https://shapenet.cs.stanford.edu/media/sampledata_220k.tar) containing kmz files can be downloaded, but I could not find a readme file or script to prepare the same training data like ./data/0/0.gz.  We will be appreciated if a script or statement for preparing training data is offered. Thanks a lot!

**Comment by xiaomingjie** [comment]
It seems that all training data has released but test data not found..Does anyone have a solution to find test data?

**Comment by AmyWan** [comment]
@jingluwang hi,Did you get the solution?

**Comment by AmyWan** [comment]
@xiaomingjie hi,could you like to share me with the code for prepareing train data,

**Comment by xiaomingjie** [comment]
@AmyWan Sorry about that, I also don't have the data-processing code. the train data comes from Hao Su Lab and they didn't open their processing approach but can only learn about the data form from `BathcFetcher.py`. And there is no test data.
